package(default_visibility = ["//visibility:public"])

cc_library(
    name = "mnist",
    srcs = ["mnist.cc"],
    hdrs = ["mnist.h"],
)

cc_test(
    timeout = "short",
    name = "mnist_test",
    srcs = ["test.cc"],
)
